version: "3"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "${PORT_BACKEND}:5000"
    environment:
      MONGODB_URI: ${MONGODB_URI}

  db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 6AVA9RtZD9F3gfTv
    ports:
      - "27017:27017"
