# Dockerfile for Backend Server (VM2)
FROM node:14-alpine

WORKDIR /app

# Copy package.json and package-lock.json separately to take advantage of Docker cache
COPY package*.json ./
RUN npm install

# Copy the rest of the application source code
COPY . .

# Expose port 5000 for the application
EXPOSE 5000

# Start the application using the "start" script defined in package.json
CMD ["npm", "start"]
